apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: model-serving-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: model-serving
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: External  # Custom metric for AI workloads
    external:
      metric:
        name: requests_per_second
        selector:
          matchLabels:
            service: model-serving
      target:
        type: AverageValue
        averageValue: 500