name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'aws/terraform/**'
      - 'gcp/pulumi/**'

jobs:
  tf-validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
    - run: |
        cd aws/terraform
        terraform validate

  pulumi-up:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pulumi/actions@v3
      with:
        command: up
        stack-name: dev
        work-dir: gcp/pulumi
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}